sprites.onDestroyed(SpriteKind.Player, function (sprite) {
    if (sprite.tileKindAt(TileDirection.Left, assets.tile`myTile`)) {
        tiles.setTileAt(sprite.tilemapLocation().getNeighboringLocation(CollisionDirection.Left), assets.tile`transparency16`)
        tiles.setWallAt(sprite.tilemapLocation().getNeighboringLocation(CollisionDirection.Left), false)
    }
})
tiles.setCurrentTilemap(tilemap`level1`)
tileUtil.setWalls(assets.tile`myTile10`, true)
tileUtil.setWalls(assets.tile`stair`, true)
let P1_mario = sprites.create(assets.image`myImage`, SpriteKind.Player)
let P2luigi = sprites.create(assets.image`myImage0`, SpriteKind.Player)
let P3toad = sprites.create(assets.image`myImage1`, SpriteKind.Player)
let P4Peach = sprites.create(assets.image`myImage2`, SpriteKind.Player)
P1_mario.setPosition(3, 24)
P2luigi.setPosition(3, 24)
P3toad.setPosition(3, 24)
controller.player1.moveSprite(P1_mario, 100, 100)
controller.player2.moveSprite(P2luigi, 100, 100)
controller.player3.moveSprite(P3toad, 100, 100)
controller.player4.moveSprite(P4Peach, 100, 100)
